zurb/foundation-apps

js/angular/components/notification/notification.js
=> Notifications: $digest already in progress

docs/templates/button.html, scss/components/_button.scss
Noticed that these colors are missing right now, but very easy to add in
=> Add info and dark colored buttons

js/angular/components/actionsheet/actionsheet.html
=> Proper actionsheet activation

docs/templates/angular.html
=> Documentation to extend DefaultController

js/angular/components/modal/modal.js, js/angular/services/foundation.core.js
=> Modal factory

js/angular/components/modal/modal.js, js/angular/components/notification/notification.js
=> Notification factory

js/angular/components/actionsheet/actionsheet-content.html, js/angular/components/actionsheet/actionsheet.js
=> Action sheet toggle off

docs/templates/forms.html, scss/components/_forms.scss
Please see #416 for explanation.
=> Adjust select padding to avoid text arrow overlap [alternative]

js/angular/components/panel/panel.js
Please see #420 for explanation.
=> Do not trigger animation when not needed

README.md
Just a minor typo in the README!
=> aseemble -> assemble

js/angular/components/popup/popup.js
Scope didn't have ability to pull in scope.
=> Gave scope a target

gulpfile.js, package.json
Update the gulp task to include templateCache of directives as per #354
=> Make a gulp task to compile all templates to a single file

js/angular/components/notification/notification.js
Reverts zurb/foundation-apps#483
=> Revert "Fixed issue with autoclose for dynamically added notifications"

js/angular/components/modal/modal.js
I made some modification in `ModalFactory`. I added a promise to resolve template request before compiling the template.
=> Fetch modal template before initialisation in ModalFactory

scss/components/_utilities.scss
=> Fixed show-for-*, hide-for-* mixins to work with ng-hide/ng-show directives

js/angular/components/actionsheet/actionsheet.js
Fix apply in progress for action sheets
=> Fix apply in progress

js/angular/components/modal/modal.js
This is to get FoundationModal service as dependancy in angular controller
=> Added FoundationModal service to foundation.modal module

js/angular/components/modal/modal.js
Modal publish close event on hideOverlay
=> Modal publish close event on hideOverlay

docs/assets/js/app.js, docs/templates/iconic.html, js/angular/components/iconic/iconic.js
Copies attributes from img to svg after injection
=> Fixes #569

js/angular/components/modal/modal.js
Set modal active state regardless of whether modal content is updated
=> Modal active fix

scss/components/_panel.scss
duplicate property causes issues with
https://github.com/ben-eb/gulp-csso
=> remove duplicate display property

js/angular/components/actionsheet/actionsheet.js
=> Fix actionsheet subscribe

gulpfile.js
Adds a few missing semicolons.
=> Updates gulpfile.js formatting

scss/components/_grid.scss
resolves https://github.com/zurb/foundation-apps/issues/707
=> move setting of grid-block height into grid-frame mixin

docs/templates/angular.html
The modified snippet is currently not rendering as it should (see http://foundation.zurb.com/apps/docs/#!/angular)
=> Update Angular overview documentation

js/angular/services/foundation.mediaquery.js
Added a check to only trim if we have quotes.
=> Some browser don't requite string style values

bin/gulp-dynamic-routing.js
Add support to have dynamic routing output angular script which adds routes during the dymanic routing module config phase.
Also adds support for routing to be run multiple times with same output file.
=> add angular support and multiple runs
