js/angular/components/common/common.js
Since the animation-cancellation feature is implemented in foundation.core service, removing the previous fix that was added in hard-toggle  directive. It is creating other issues.
For example, if we click on left panel and then immediately click on right panel in docs, right panel never show up because it is cancelled in hard-toggle directive.
=> Undoing the fix for #323 implemented before animation cancellation

js/angular/components/common/common.js
In the current implementation id passed to zf-close is not considered.
Fixing this
=> Fixed issue in zf-close #363

bower.json, gulpfile.js
UI router doc states the bower package is angular-ui-router
https://github.com/angular-ui/ui-router#get-started
If most people follow this doc, they will end up with 2 dependencies ui-router and angular-ui-router
=> Renamed the ui-router bower dependency to angular-ui-router 

js/angular/components/modal/modal.js
Should solve #192. Putting the focus back on the originating element is not possible right now since there might not be an originating element (such as when programmatically triggered). To enable triggering a refocus, the `zf-open` and `zf-toggle` directives would have to be redone.
=> Focus modal on show

docs/index.html
Documentation pages not scrolling to top of page.
It's a minor one, but a bit annoying when reading the docs. 
https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-view
=> Set autoscroll on ui-view

docs/templates/menu-bar.html
Extending the menu bar by copying from the documentation was failing due to duplicate mixin parameter.
=> Correct duplicate menu-bar-style mixin parameter

js/angular/components/popup/popup.js
With the above two lines the pinAt value is actually passed on to the tether instance. It seems that the pinAt property was already meant for passing the targetAttachment of the tether instance that is created in popup.js.
=> use pinAt to pass targetAttachment in popup directive

js/angular/services/foundation.dynamicRouting.js
Provide access to add custom data to state objects from front matter.  I needed to add custom data for route authentication, but this could be useful for others and their purposes as well.
Template Front Matter
```html
---
name: main
url: /
animationIn: fadeIn
data: { requiresLogin: true }
---
```
Added to DynamicRouting 
```javascript
angular.extend(state.data, page.data);
```
=> Add custom data to states from front matter

scss/components/_menu-bar.scss
These alignment classes will allow menubar menu items to "float"  right, center, justified, and spaced.
=> Added alignment classes to menu bars in order to align menu items

gulpfile.js
The dist/foundation.js should not include bower_components files. I separated out the bower_components dependency JS files into it's own part of the build process.
=> Gulp dist bower_components

js/angular/components/popup/popup.js
When you publish a 'hide' event, newTarget is undefined, resulting in an error being thrown.
=> newTarget is not defined error on publish event in Popup

js/angular/app.js, js/angular/components/iconic/iconic.js, js/angular/vendor/svgDirs.js
First off, I'm new to using GitHub, so forgive me if I'm not following the proper practices for submitting requests.
I recently switched a project I built using Foundation for Apps to use HTML5 mode, mainly for prettier urls.  I followed the instructions laid out in the [documentation](https://docs.angularjs.org/guide/$location).  After doing so, I noticed the iconic SVGs weren't loading properly.  After some investigation I found that the issue was caused by the iconic urls only containing hash fragments.  As called out in the HTML5 mode documentation:
>There is one exception: Links that only contain a hash fragment (e.g. `<a href="#target">`) will only change $location.hash() and not modify the url otherwise.
For more info see AngularJS issue …
=> Updates to iconic directive to broadcast when svg injection is completed

js/angular/services/foundation.dynamicRouting.js
`params` is initialized to an array, but is used as an object. This results in the DefaultController's $scope.params property to be invalid. More detail can be found here: https://github.com/zurb/foundation-apps/issues/437
=> Fix params initialization in DefaultController

js/angular/components/iconic/iconic.js
We are using the paid version of the awesome [Iconic](https://useiconic.com/) icons. Thus the default ```assetPath``` in the ```iconic``` service doesn't necessarily fit.
So I changed the service to a provider that can be configured via ```IconicProvider.setAssetPath(path)```. If no ```path``` is configured, the default value ```assets/img/iconic/``` is used.
=> feat(Iconic): add provider to make 'assetPath' configurable

js/angular/components/modal/modal.js
Updated modal.js to fix a bug where somehow scope.$root could be null after a state change.
=> Update modal.js where scope.$root is null

js/angular/components/notification/notification.js
The autoclose functionality never triggers because scope.active is only set to true after the timeout on line 146, thus scope.active on line 160 (line 168 new) is always false and thus the autoclose timeout is never triggered.  Adding the autoclose timeout after setting scope.active to true resolves this issue.
=> Fixed issue with autoclose for dynamically added notifications

bin/gulp-dynamic-routing.js
I have two apps I built with F4A, each with their own gulp file.  All common logic for building the apps are in a single gulp file outside the root directory of those two apps.  That single gulp files uses F4A's gulp-dynamic-routing.  In order to support this layout, I need the root directory to be configurable in the routing plugin.
=> Allow configuring root directory for gulp-dynamic-routing

js/angular/components/modal/modal.js
Provide ability to check whether or not the modal is active
=> Add isActive method to ModalFactory

js/angular/components/modal/modal.js
This adds another case to property handling in ModalFactory. 
Using white-listed config property "overlayClose" with ModalFactory did not work, because the attribute was rendered as-is (camelCase), thus getting ignored during compilation of the directive element.
Unfortunately we cannot use attrs.$normalize() in ModuleFactory because we're outside the directive and link() function.
=> Add case for "overlayClose" -> "overlay-close" ModalFactory property

docs/assets/js/app.js, docs/partials/examples-dynamic-modal.html, docs/templates/modal.html, js/angular/components/modal/modal.js, scss/components/_forms.scss
Extend ModalFactory configuration to allow creation of dialog modals by
adding dialog class to dynamically generated element.  This change allows creating a dialog modal via the ModalFactory by providing the following configuration:
```js
var modal = new ModalFactory({
dialog: true,
...
});
```
This PR and #561 should be reviewed together as they both deal with adding classes to the generated modal.  This PR is specific to allowing the **dialog** class to be added, while the other is generic and allows any class to be added.
=> Allow ModalFactory to create dialog modals

js/angular/services/foundation.core.animation.js
I originally thought it was due to the display property being set to none for the panels, which is sort of true, but I believe now that the root cause is the panel's animation event listener.  It was picking up the transitionend events for the child zf-open button element, it transform's the background-color property.  
Since the transition for the button color occurs rather quickly, the panel runs finishAnimation too soon, setting the display property to none and canceling the transitionend event for the the child panel.
All in all, I think it be tighter if the element would verify that the `transitionend` event to execute on is for the transition on itself as the target.  Allowing panels to support child elements with transitions/animations without effecting it's own.
Instead of …
=> Possible fix for issue 481

bower.json
Per https://github.com/bower/bower.json-spec/pull/43 / https://github.com/bower/bower.json-spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99, which has finally brought clarity regarding `main`. In particular:
> * Use source files with module exports and imports over pre-built distribution files.
Also, in the spec's example, the CSS files aren't included in `main`, but the main SCSS file is.
=> Fix stylesheet portion of bower.json to comply w/ new `main` spec

scss/helpers/_images.scss
Windows 7 64 
IE 11
IE 11 applied fix
also works in other browsers, on mobile too, I didn't test on Safari 7+ (not a mac user)
here a nice convertor http://codepen.io/yoksel/details/JDqvs/ thanks to the creator
the code sure doesn't look nice but is compatible with all browsers including IE10 and 11
=> IE10 11 select arrow svg fix

js/angular/components/common/common.js
This can cause console errors in some circumstances.
=> Fixes check for undefined on Hammer elements.

docs/templates/modal.html
The dialog modal code section said zf-open="animatedModal" instead of dialogModal
=> Typo in dialogModal code column

js/angular/components/modal/modal.js
The issue with modal close (including scope and element variables sometimes being undefined as noted in @soumak77's pr) seems to be stemming from the use of setTimeout with a 3 second delay instead of $timeout with no delay. Using $timeout without a delay also eliminates errors when trying to destroy modals immediately before redrawing them which appears necessary when changing the content scope of modals created using ModalFactory.
=> Fix modal destroy issues

docs/templates/notification.html
I tried to customize notifications as suggested in documentation and I notice an error in mixin name.
[`here`](http://foundation.zurb.com/apps/docs/#!/notification) in Sass Mixins section
```notification-layout -> notification-style```
cheers
=> Correct notification mixin name in documentation

bower.json
based on conversations in https://github.com/zurb/foundation-apps/issues/694#issuecomment-149650049. bumping to to a lower bound of 1.4.7 doesn't have any issues.
Closes #694
=> deps: version bump on angular libs

js/angular/components/modal/modal.js
overlayClose attribute could not be set to false. See #638
=> Fixes setting overlayClose attr in modalFactory

js/angular/components/notification/notification-static.html, js/angular/components/notification/notification.html
In order to be able to inject html in notifications I just moved the title variable inside the ng-bind-html directive. Please see https://github.com/zurb/foundation-apps/issues/692.
=> Moved title into the ng-bind-html attribute.
